//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinterCricket.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BowlingType
    {
        public BowlingType()
        {
            this.IndividualScores = new HashSet<IndividualScore>();
        }
    
        public int BowlingTypeId { get; set; }
        public string BowlingType1 { get; set; }
    
        public virtual ICollection<IndividualScore> IndividualScores { get; set; }
    }
}
