//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinterCricket.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HowOut
    {
        public HowOut()
        {
            this.IndividualScores = new HashSet<IndividualScore>();
        }
    
        public int HowOutId { get; set; }
        public string HowOut1 { get; set; }
    
        public virtual ICollection<IndividualScore> IndividualScores { get; set; }
    }
}
