//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinterCricket.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualScore
    {
        public int ScoreId { get; set; }
        public Nullable<int> BallsFaced { get; set; }
        public Nullable<int> RunsScored { get; set; }
        public Nullable<int> OversBowled { get; set; }
        public Nullable<int> BowlingType { get; set; }
        public Nullable<int> WicketTaken { get; set; }
        public Nullable<int> Six { get; set; }
        public Nullable<int> Fours { get; set; }
        public Nullable<int> RunsGiven { get; set; }
        public Nullable<int> HowOut { get; set; }
        public Nullable<int> BowledBy { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> MatchId { get; set; }
        public Nullable<int> PlayerId { get; set; }
    
        public virtual BowlingType BowlingType1 { get; set; }
        public virtual HowOut HowOut1 { get; set; }
        public virtual Member Member { get; set; }
        public virtual Team Team { get; set; }
        public virtual Match Match1 { get; set; }
        public virtual Member Member11 { get; set; }
    }
}
