//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinterCricket.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchStat
    {
        public int MatchStatsId { get; set; }
        public Nullable<int> MatchId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> RunsScored { get; set; }
        public Nullable<int> ExtraScored { get; set; }
        public Nullable<double> OversReceived { get; set; }
        public Nullable<int> WicketsLost { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Team Team { get; set; }
    }
}
