//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinterCricket.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.IndividualScores = new HashSet<IndividualScore>();
            this.IndividualScores11 = new HashSet<IndividualScore>();
        }
    
        public int MemberId { get; set; }
        public string Name { get; set; }
        public Nullable<int> MemberType { get; set; }
        public Nullable<int> Team { get; set; }
        public Nullable<int> PlayerType { get; set; }
        public Nullable<int> PlayingHand { get; set; }
        public Nullable<bool> IsWicketKeeper { get; set; }
        public Nullable<bool> HasChangedTeamEver { get; set; }
        public Nullable<bool> IsCaptain { get; set; }
    
        public virtual ICollection<IndividualScore> IndividualScores { get; set; }
        public virtual MemberType MemberType1 { get; set; }
        public virtual PlayingHand PlayingHand1 { get; set; }
        public virtual PlayerType PlayerType1 { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual ICollection<IndividualScore> IndividualScores11 { get; set; }
    }
}
