//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinterCricket.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Series
    {
        public Series()
        {
            this.Matches = new HashSet<Match>();
        }
    
        public string SeriesName { get; set; }
        public int SeriesId { get; set; }
        public Nullable<System.DateTime> SeriesValidFrom { get; set; }
        public Nullable<System.DateTime> SeriesValidTo { get; set; }
    
        public virtual ICollection<Match> Matches { get; set; }
    }
}
