//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinterCricket.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public Venue()
        {
            this.Matches = new HashSet<Match>();
        }
    
        public int VenueId { get; set; }
        public string Name { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string StateId { get; set; }
        public string Suburb { get; set; }
        public Nullable<int> PostCode { get; set; }
    
        public virtual ICollection<Match> Matches { get; set; }
    }
}
