//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinterCricket.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WinningMode
    {
        public WinningMode()
        {
            this.Results = new HashSet<Result>();
        }
    
        public int WinningModeId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Result> Results { get; set; }
    }
}
